
SECRET_KEY: 'sk_test_Aa8pcVrWT8rR3VfpyPHMFk5g000pmnXCjV'
PUBLISHABLE_KEY: 'pk_test_HVwuFu4RsXfJAX94FGYZXhWy00rRSVAqH9'

GMAIL_ADDRESS: "ryanspetsittingtucson@gmail.com"
GMAIL_PASSWORD: "SR408@Panda1!"

AWS_ACCESS_KEY: "AKIAY4MG2OJNJUDSRZ4R"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "sitting-ryan-heckman"