
SECRET_KEY: 'sk_test_Aa8pcVrWT8rR3VfpyPHMFk5g000pmnXCjV'
PUBLISHABLE_KEY: 'pk_test_HVwuFu4RsXfJAX94FGYZXhWy00rRSVAqH9'

GMAIL_ADDRESS: "ryanspetsittingtucson@gmail.com"
GMAIL_PASSWORD: "SR408@Panda1!"